theme: jekyll-theme-cayman

# Site settings
title: Fei
email: gaofei@hdu.edu.cn
description: Homepage
# baseurl: "/index"
# url: "https://fei-gao.github.io"

# Build settings
# # markdown: kramdown
# permalink: pretty

# highlighter: rouge
# kramdown:
#   input: GFM
#   auto_ids: true
#   syntax_highlighter: rouge